# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(677, 358)
        font = QtGui.QFont()
        font.setFamily("Pretendard Variable")
        Dialog.setFont(font)
        self.pushButton_Get_DecryptedFile = QtWidgets.QPushButton(Dialog)
        self.pushButton_Get_DecryptedFile.setGeometry(QtCore.QRect(70, 170, 80, 23))
        self.pushButton_Get_DecryptedFile.setObjectName("pushButton_Get_DecryptedFile")
        self.pushButton_Get_EncryptedFile = QtWidgets.QPushButton(Dialog)
        self.pushButton_Get_EncryptedFile.setGeometry(QtCore.QRect(420, 170, 80, 23))
        self.pushButton_Get_EncryptedFile.setObjectName("pushButton_Get_EncryptedFile")
        self.pushButton_Encrypt = QtWidgets.QPushButton(Dialog)
        self.pushButton_Encrypt.setGeometry(QtCore.QRect(300, 70, 80, 23))
        self.pushButton_Encrypt.setObjectName("pushButton_Encrypt")
        self.pushButton_Decrypt = QtWidgets.QPushButton(Dialog)
        self.pushButton_Decrypt.setGeometry(QtCore.QRect(300, 100, 80, 23))
        self.pushButton_Decrypt.setObjectName("pushButton_Decrypt")
        self.pushButton_new_key = QtWidgets.QPushButton(Dialog)
        self.pushButton_new_key.setGeometry(QtCore.QRect(510, 280, 80, 23))
        self.pushButton_new_key.setObjectName("pushButton_new_key")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 250, 91, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(96, 280, 101, 20))
        self.label_2.setObjectName("label_2")
        self.textEdit_public_key = QtWidgets.QTextEdit(Dialog)
        self.textEdit_public_key.setEnabled(False)
        self.textEdit_public_key.setGeometry(QtCore.QRect(200, 250, 290, 21))
        self.textEdit_public_key.setObjectName("textEdit_public_key")
        self.textEdit_private_key = QtWidgets.QTextEdit(Dialog)
        self.textEdit_private_key.setEnabled(False)
        self.textEdit_private_key.setGeometry(QtCore.QRect(200, 280, 290, 21))
        self.textEdit_private_key.setObjectName("textEdit_private_key")
        self.plainTextEdit_Decrypted = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_Decrypted.setGeometry(QtCore.QRect(70, 40, 191, 121))
        self.plainTextEdit_Decrypted.setPlainText("")
        self.plainTextEdit_Decrypted.setObjectName("plainTextEdit_Decrypted")
        self.plainTextEdit_Encrypted = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_Encrypted.setGeometry(QtCore.QRect(420, 40, 190, 121))
        self.plainTextEdit_Encrypted.setReadOnly(True)
        self.plainTextEdit_Encrypted.setObjectName("plainTextEdit_Encrypted")
        self.pushButton_Save_DecryptedFile = QtWidgets.QPushButton(Dialog)
        self.pushButton_Save_DecryptedFile.setGeometry(QtCore.QRect(180, 170, 80, 23))
        self.pushButton_Save_DecryptedFile.setObjectName("pushButton_Save_DecryptedFile")
        self.pushButton_Save_EncryptedFile = QtWidgets.QPushButton(Dialog)
        self.pushButton_Save_EncryptedFile.setGeometry(QtCore.QRect(530, 170, 80, 23))
        self.pushButton_Save_EncryptedFile.setObjectName("pushButton_Save_EncryptedFile")
        self.label_error_msg = QtWidgets.QLabel(Dialog)
        self.label_error_msg.setGeometry(QtCore.QRect(20, 330, 631, 16))
        self.label_error_msg.setText("")
        self.label_error_msg.setObjectName("label_error_msg")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "RSA Encryption / Decryption Test"))
        self.pushButton_Get_DecryptedFile.setText(_translate("Dialog", "Get File"))
        self.pushButton_Get_EncryptedFile.setText(_translate("Dialog", "Get File"))
        self.pushButton_Encrypt.setText(_translate("Dialog", "Encrypt ->"))
        self.pushButton_Decrypt.setText(_translate("Dialog", "<- Decrypt"))
        self.pushButton_new_key.setText(_translate("Dialog", "New Key"))
        self.label.setText(_translate("Dialog", "Public Key: "))
        self.label_2.setText(_translate("Dialog", "Private Key: "))
        self.pushButton_Save_DecryptedFile.setText(_translate("Dialog", "Save to File"))
        self.pushButton_Save_EncryptedFile.setText(_translate("Dialog", "Save to File"))
